# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ioTsTvXnnU4VQQ29DU-xR0bzoz5smMkX
"""

#importar biblioteca pandas
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/carlosfab/curso_data_science_na_pratica/master/modulo_02/BBAS3.SA.csv')

df.head()

df.shape

df["Close"].std()

df.columns

df.describe()

df['High'].plot()